--1.Total number of customers?
select COUNT(*) as cust_num from customers

--2.Show transactions for Chennai market.
SELECT * FROM transactions
WHERE market_code = 'Mark001'

--3.Show distrinct product codes that were sold in chennai
SELECT DISTINCT(product_code)
FROM transactions
WHERE market_code = 'Mark001'

--4.Show transactions where currency is US dollars
SELECT * FROM transactions
WHERE currency = 'USD'

--5.Show transactions in 2020 join by date table
SELECT t.*, d.*
FROM transactions AS t
JOIN date AS d
ON t.order_date = d.date
WHERE d.year = 2020

--6.Show total revenue in year 2020
SELECT SUM(t.sales_amount)
FROM transactions AS t
INNER JOIN date AS d
ON t.order_date = d.date
WHERE d.year = 2020 

--7.Show total revenue in year 2020, January Month
SELECT SUM(t.sales_amount)
FROM transactions AS t
INNER JOIN date AS d
ON t.order_date = d.date
WHERE d.year = 2020 and d.month_name = 'January'

--8.Show total revenue in year 2020 in Chennai
SELECT SUM(t.sales_amount) AS Revenue
FROM transactions AS t
INNER JOIN date AS d
ON t.order_date = d.date
WHERE d.year = 2020 and t.market_code = 'Mark001'

--9. Show the top 5 customers with the highest total sales amount.
SELECT top 5 t.customer_code,  SUM(t.sales_amount) AS total_sales
FROM transactions AS t
JOIN customers AS c
ON t.customer_code = c.customer_code
GROUP BY t.customer_code
ORDER BY total_sales DESC

--10. Show the total revenue generated by each market.
SELECT m.markets_name, SUM(t.sales_amount) AS Revenue
FROM transactions AS t
JOIN markets AS m
ON t.market_code = m.markets_code
GROUP BY m.markets_name
ORDER BY Revenue DESC

--11.Show the monthly sales trend for the year 2018.
SELECT d.month_name AS months, SUM(t.sales_amount) AS sales
FROM transactions AS t
JOIN date AS d
ON t.order_date = d.date
WHERE d.year = 2018
GROUP BY d.month_name
ORDER BY months

--12.Show the top 5 products with the highest quantity sold.
SELECT top 5 p.product_code, SUM(t.sales_qty) AS sales_qty
FROM transactions AS t
JOIN products AS p
ON t.product_code = p.product_code
GROUP BY p.product_code
Order BY sales_qty DESC

--13.Show the average sales amount per customer for each market.
SELECT top 10 m.markets_name, t.customer_code,floor(AVG(t.sales_amount)) AS 'average_sales'
FROM transactions AS t
JOIN markets AS m
ON t.market_code = markets_code
GROUP BY m.markets_name, t.customer_code
ORDER BY t.customer_code

--14.Show top 5 product with highest avg cost price 
select top 5 product_code,ceiling(avg(cost_price)) as avg_cost_price from transactions
group by product_code
order by avg_cost_price desc

--15.Show top 5 product with highest profit margin.
select top 5 product_code, sum(profit_margin) as max_profit_margin from transactions
group by product_code
order by max_profit_margin desc








